// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Checkout product', function() {
  this.timeout(30000)
  let driver
  beforeEach(async function() {
    driver = await new Builder().forBrowser('firefox').build()
    // driver = await new Builder().forBrowser('chrome').build();

  })
  afterEach(async function() {
    await driver.close()
  })

  it('Checkout product', async function() {
    await driver.get("https://www.saucedemo.com/")
    // await driver.manage().window().setRect({ width: 1024, height: 768 })
    await driver.findElement(By.css("*[data-test=\"username\"]")).click()
    await driver.findElement(By.css("*[data-test=\"username\"]")).sendKeys("standard_user")
    await driver.findElement(By.css("*[data-test=\"password\"]")).click()
    await driver.findElement(By.css("*[data-test=\"password\"]")).sendKeys("secret_sauce")
    await driver.findElement(By.css("*[data-test=\"login-button\"]")).click()
    assert(await driver.findElement(By.css("*[data-test=\"title\"]")).getText() == "Products")
    await driver.findElement(By.css("*[data-test=\"add-to-cart-sauce-labs-bike-light\"]")).click()
    await driver.findElement(By.css("*[data-test=\"add-to-cart-sauce-labs-bolt-t-shirt\"]")).click()
    await driver.findElement(By.css("*[data-test=\"add-to-cart-sauce-labs-fleece-jacket\"]")).click()
    await driver.findElement(By.css("*[data-test=\"add-to-cart-sauce-labs-onesie\"]")).click()
    await driver.findElement(By.css("*[data-test=\"add-to-cart-test.allthethings()-t-shirt-(red)\"]")).click()
    assert(await driver.findElement(By.css("*[data-test=\"remove-test.allthethings()-t-shirt-(red)\"]")).getText() == "Remove")
    await driver.findElement(By.css("*[data-test=\"shopping-cart-link\"]")).click()
    assert(await driver.findElement(By.css("*[data-test=\"title\"]")).getText() == "Your Cart")
    await driver.findElement(By.css("*[data-test=\"checkout\"]")).click()
    assert(await driver.findElement(By.css("*[data-test=\"title\"]")).getText() == "Checkout: Your Information")
    await driver.findElement(By.css("*[data-test=\"firstName\"]")).click()
    await driver.findElement(By.css("*[data-test=\"firstName\"]")).sendKeys("tester")
    await driver.findElement(By.css("*[data-test=\"lastName\"]")).click()
    await driver.findElement(By.css("*[data-test=\"lastName\"]")).sendKeys("data")
    await driver.findElement(By.css("*[data-test=\"postalCode\"]")).click()
    await driver.findElement(By.css("*[data-test=\"postalCode\"]")).sendKeys("0000")
    await driver.findElement(By.css("*[data-test=\"continue\"]")).click()
    assert(await driver.findElement(By.css("*[data-test=\"title\"]")).getText() == "Checkout: Overview")
    await driver.findElement(By.css("*[data-test=\"total-label\"]")).click()
    await driver.findElement(By.css("*[data-test=\"finish\"]")).click()
    assert(await driver.findElement(By.css("*[data-test=\"complete-header\"]")).getText() == "Thank you for your order!")
    await driver.findElement(By.css("*[data-test=\"back-to-products\"]")).click()
    await driver.findElement(By.id("react-burger-menu-btn")).click()
    await driver.findElement(By.css("*[data-test=\"logout-sidebar-link\"]")).click()
  })
})
